name: spoti_clon

description: A new Flutter project.

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  audiotagger: ^2.2.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  file_picker: ^5.0.1
  mysql1: ^0.19.2  
  flutter_dotenv: ^5.0.2

  english_words: ^4.0.0
  provider: ^6.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


